config/routes.rb
Rails.application.routes.draw do
  resources :jenis_proses
  get 'role_denieds/index', as: "role_denieds"
  get 'invoices/index'
  root 'home#index'
  
  resources :trash_recordings
  resources :customer_achievements, only: [:index] do 
    collection do
      get :transaction_list
    end
  end
  resources :inventory_histories
  resources :customers
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders do 
    collection do 
      get :add_item
      get :get_customers
      get :get_jenis_proses
      get :autocomplete_customer_customer_name
      get :confirm_new
      post :confirm_new
      get :print_count
      get :login_print
      post :login_check_print
    end
  end
  resources :inventories do
    collection do
      get ':id/add', action: :add, as: :add
    end
  end
  resources :order_ins
  resources :order_outs
  resources :invoices do
    collection do
      get ':id/detail', action: :detail
      get :transaction_list
      get :print_count
      get :login_print
      post :login_check_print
    end
  end

  resources :roles do
    collection do 
      post ':id/update_role_user', action: :update_role_user, :as => :update_role_user
    end
  end

  get 'dashboard', to: 'home#index', as: 'dashboard'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/controllers/order_ins_controller.rb
class OrderInsController < ApplicationController
  before_action :current_user
  before_action :get_params_header, only: [:index]
  before_action :get_list_order_items, only: [:index]
  before_action :authenticate_user
  before_action :check_role_user

  def index; end

  private

  def get_list_order_items
    @orders      = OrderItemDetail.search('progress', params[:search], params[:start_date], params[:end_date], params[:jenis_proses])
    @order_items = @orders.page(params[:page]).per(params[:per_page])
  end

  def get_params_header
    @start_date = params[:start_date].present? ? params[:start_date] : Date.today - 7.days
    @end_date = params[:end_date].present? ? params[:end_date] : Date.today
    @jenis_proses = JenisProse.order(:jenisproses_name).map{|v| [v.code_name, v.id]}
  end
end

app/helpers/order_ins_helper.rb
module OrderInsHelper
end

app/views/order_ins/_list.html.erb
<% if notice.present? %>
  <div class="row">
    <div class="col-md-12">
      <div class="warning-section">
        <div class="warning-icon">
          <i class="icon icon-attention"></i>
        </div>
        <p>
          <%= notice %>
        </p>
      </div>
    </div>
  </div>
<% end %>

<div class="card-white card-table">
  <div class="header-card">
    <div class="header-card-title">
      <div style="display: flex; align-items: center;">
        <span class="header-icon"><i class="icon icon-basket"></i></span>
        <h4>Barang Masuk</h4>
      </div>
      <div>
        <%= link_to raw("<i class='icon icon-print'></i> Print"), "javascript:voide(0);", :"data-link" => new_inventory_history_path, :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Buat Pengeluaran Barang", class: "btn btn-success btn-custom launch-modal-inventory" %>
      </div>
    </div>
  </div>
  <div class="body-card">
    <%= form_for(order_ins_path, method: :get, remote: true) do %>
      <div class="row filter">
        <div class="col-md-6">
          <span>Show</span>
          <%= select_tag "per_page", options_for_select([[10, 10], [20, 20], [30, 30], [40, 40]], params[:per_page]), {class: "form-control show-entries"} %>
          <span>Entries</span>
        </div>
        <div class="col-md-6">
          <div class="form-group row">
            <label for="searcho" class="col-sm-2 col-form-label" style="text-align:right; padding-right:2px;">Search:</label>
            <div class="col-sm-5">
              <div class="input-group">
                <%= select_tag :jenis_proses, options_for_select(@jenis_proses, params[:jenis_proses]), include_blank: "Pilih Jenis Proses", class: "form-control", style: "height:30px;" %>
              </div>
            </div>
            <div class="col-sm-5"> 
              <div class="input-group">
                <%= text_field_tag "search", {}, class: "form-control", placeholder:"cari berdasakan nama customer atau nomor pesanan", value: params[:search] %>
                <div class="input-group-append">
                  <button type="submit"class="btn btn-outline-default btn-search" type="button"><i class="icon icon-search"></i></button>
                </div>
                <%= hidden_field_tag 'start_date', @start_date.to_date.strftime("%d-%m-%Y") %>
                <%= hidden_field_tag 'end_date', @end_date.to_date.strftime("%d-%m-%Y") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="table-responsive center">
      <table class="table table-hover table-bordered">
        <thead>
          <th>No</th>
          <th>Tanggal Pemesanan</th>
          <th>Nama Customer</th>
          <th>Nomor Pesanan / No. Surat Jalan</th>
          <th>Barang</th>
          <th>Proses</th>
          <th>Qty</th>
          <th>Harga Satuan</th>
          <th>Total Harga</th>
          <th>Status Barang</th>
          <!-- <th>Action</th> -->
        </thead>
        <% if order_items.blank? %>
          <tr><td colspan="11" class="center"> Tidak ada data barang masuk </td></tr>
        <% end %>
        <% order_items.each_with_index do |order, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= (order.date_in + 7.hours).strftime("%d %b %Y %H:%M:%S") %></td>
            <td><%= order.customer_name %></td>
            <td><%= order.inv_number %></td>
            <td><%= order.product_name %></td>
            <td><%= order.process_name %></td>
            <td><%= order.qty %></td>
            <td><%= order.unit_price %></td>
            <td><%= order.item_total_price %></td>
            <td><%= order.status_order_item %></td>
            <!-- <td>
              <%= link_to raw("<i class='icon icon-search'></i>"), "javascript:void();", :'data-link' => order_path(order), :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Detail Transaksi | #{order.inv_number}", class: "btn btn-info btn-action launch_modal" %>
              <%= link_to raw("<button class='btn btn-outline-warning btn-action'><i class='icon icon-edit'></i></button>"), edit_order_path(order.id) %>
              <%= link_to raw("<button class='btn btn-danger btn-action'><i class='icon icon-trash'></i></button>"), orders_path+"/"+order.id.to_s, method: :delete, data: {confirm: "Are you sure ?"} %>
            </td> -->
          </tr>
        <% end %>
      </table>

      <div style="display:flex; justify-content: center;">
        <%= paginate order_items %>
      </div>
      <%= page_entries_info order_items, :entry_name => "Order Barang" %>
    </div>
  </div>
</div>

<div class="modal fade" id="modal_show" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document" style="max-width: 990px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Print Order Ins <%= "#{params[:start_date]} - #{params[:end_date]}" if params[:start_date].present? %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="table-responsive center">
          <table class="table table-hover table-bordered">
            <thead>
              <th>No</th>
              <th>Tanggal Pemesanan</th>
              <th>Nama Customer</th>
              <th>Nomor Pesanan / No. Surat Jalan</th>
              <th>Barang</th>
              <th>Proses</th>
              <th>Status Barang</th>
              <th>Harga Satuan</th>
              <th>Qty</th>
              <th>Total Harga</th>
              <!-- <th>Action</th> -->
            </thead>
            <% if orders.blank? %>
              <tr><td colspan="11" class="center"> Tidak ada data barang masuk </td></tr>
            <% end %>
            <% total_qty = 0; total_item_price=0; %>
            <% orders.each_with_index do |order, index| %>
              <% total_qty        += order.qty %>
              <% total_item_price += order.item_total_price %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= (order.date_in + 7.hours).strftime("%d %b %Y %H:%M:%S") %></td>
                <td><%= order.customer_name %></td>
                <td><%= order.inv_number %></td>
                <td><%= order.product_name %></td>
                <td><%= order.process_name %></td>
                <td><%= order.status_order_item %></td>
                <td><%= order.unit_price %></td>
                <td><%= number_to_rupiah(order.qty) %></td>
                <td><%= number_to_rupiah(order.item_total_price) %></td>
                <!-- <td>
                  <%= link_to raw("<i class='icon icon-search'></i>"), "javascript:void();", :'data-link' => order_path(order), :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Detail Transaksi | #{order.inv_number}", class: "btn btn-info btn-action launch_modal" %>
                  <%= link_to raw("<button class='btn btn-outline-warning btn-action'><i class='icon icon-edit'></i></button>"), edit_order_path(order.id) %>
                  <%= link_to raw("<button class='btn btn-danger btn-action'><i class='icon icon-trash'></i></button>"), orders_path+"/"+order.id.to_s, method: :delete, data: {confirm: "Are you sure ?"} %>
                </td> -->
              </tr>
            <% end %>
            <tr>
              <td colspan="8" style="text-align: center;">Total</td>
              <td class="center"><%= number_to_rupiah(total_qty) %></td>
              <td class="center"><%= number_to_rupiah(total_item_price) %></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <a href='javascript:void(0)'>
          <button type='button' class='btn btn-primary btn-custom print' onclick="print()">Print</button>
        </a>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "filter_date.js" %>

app/views/order_ins/index.html.erb
<%= render'list', order_items: @order_items, orders: @orders %>

app/views/order_ins/index.js.erb
$('.main-content').html("<%= escape_javascript(render('list', order_items: @order_items, orders: @orders)) %>")
$('.time-filter').html("<%= params[:start_date].to_date.strftime('%d %b %Y') %> <%= ' - ' + params[:end_date].to_date.strftime('%d %b %Y') if params[:end_date].present? %>")
$("#filter-start-date").val("<%= params[:start_date] %>")
$("#filter-end-date").val("<%= params[:end_date] %>")