config/routes.rb
Rails.application.routes.draw do
  resources :jenis_proses
  get 'role_denieds/index', as: "role_denieds"
  get 'invoices/index'
  root 'home#index'
  
  resources :trash_recordings
  resources :customer_achievements, only: [:index] do 
    collection do
      get :transaction_list
    end
  end
  resources :inventory_histories
  resources :customers
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders do 
    collection do 
      get :add_item
      get :get_customers
      get :get_jenis_proses
      get :autocomplete_customer_customer_name
      get :confirm_new
      post :confirm_new
      get :print_count
      get :login_print
      post :login_check_print
    end
  end
  resources :inventories do
    collection do
      get ':id/add', action: :add, as: :add
    end
  end
  resources :order_ins
  resources :order_outs
  resources :invoices do
    collection do
      get ':id/detail', action: :detail
      get :transaction_list
      get :print_count
      get :login_print
      post :login_check_print
    end
  end

  resources :roles do
    collection do 
      post ':id/update_role_user', action: :update_role_user, :as => :update_role_user
    end
  end

  get 'dashboard', to: 'home#index', as: 'dashboard'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :current_user
  before_action :authenticate_user
  before_action :check_role_user
  before_action :get_params_header
  before_action :get_list_invoices, only: [:index]
  before_action :find_invoice, only: [:show, :detail, :edit, :update, :destroy]
  before_action :get_header_params, only: [:new]
  def index
  end

  def show
    render layout: false
  end

  def detail
    @hide_filter = true    
  end

  def edit
    render layout: false
  end

  def update
    respond_to do |format|
      if params[:post][:status_invoice] == "done"
        InvoiceMaster.make_invoice_done(@invoice.id)
        format.js {redirect_to invoices_path}
      end
    end
  end

  def new
    @invoice = InvoiceMaster.new
  end

  def transaction_list
    id_customer     = params[:id_customer]
    @customer       = Customer.find(id_customer)
    @order_invoices = OrderInvoice.where(customer_id: id_customer, status_payment: "debt")

    render layout: false
  end

  def create
    if params_post[:invoice_details_attributes].blank?
      flash[:notice] = "Invoice gagal dibuat, pilih minimal satu transaksi customer!"
      redirect_to new_invoice_path
    else
      params_save = InvoiceMaster.generate_invoice(params_post)
      invoice     = InvoiceMaster.new(params_save)
      if invoice.save
        flash[:notice] = "Invoice barhasil dibuat!"
        redirect_to invoice_path(invoice.id)+"/detail"
      else
        flash[:notice] = "Invoice gagal dibuat, cobalah beberapa saat lagi atau hubungi admin!"
        redirect_to new_invoice_path
      end
    end
  end

  def destroy
    invoice_details = InvoiceDetail.where(invoice_master_id: @invoice.id)
    if invoice_details.destroy_all
      if @invoice.destroy
        respond_to do |format|
          format.html { redirect_to invoices_url, notice: 'Invoice berhasil dihapus' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to invoices_url, notice: 'Invoice gagal dihapus' }
          format.json { head :no_content }
        end
      end
    end
  end

  def print_count
    find_invoice
    if @invoice.update(params_post)
      render :html => "berhasil"
    else
      render :html => "gagal"
    end
  end

  def login_print
    render layout: false
  end

  def login_check_print
    user = User.find_by_email(params[:email])
    @login = (user && user.authenticate(params[:password])) ? true : false
    if @login
      menus_role = Menu.where("id in (?)", user.role.role_users.pluck(:menu_id)).pluck(:menu_name)
      @login = menus_role.include?("Print Twice") ? true : false
    end
  end

  private

  def get_params_header
    @start_date = params[:start_date].present? ? params[:start_date] : Time.now - 7.days
    @end_date = params[:end_date].present? ? params[:end_date] : Time.now
  end

  def get_list_invoices
    @invoices = InvoiceMaster.search(params[:search], params[:start_date], params[:end_date]).page(params[:page]).per(params[:per_page]).order("invoice_masters.id desc")
  end

  def find_invoice
    @invoice = InvoiceMaster.find(params[:id])
  end

  def get_header_params
    @customers = Customer.order(:customer_name)
  end

  def params_post
    params.require("post").permit!
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def find_invoice_detail(invoice_master_id)
    scope = InvoiceMaster.joins("LEFT JOIN invoice_details on invoice_details.invoice_master_id = invoice_masters.id").joins("LEFT JOIN order_invoices on order_invoices.id = invoice_details.order_invoice_id").joins("LEFT JOIN order_item_details on order_item_details.invoice_number = order_invoices.invoice_number").select("invoice_masters.invoice_master_code, invoice_masters.total_invoice, invoice_masters.status_invoice, order_invoices.invoice_number as order_number, order_invoices.total_item as order_total_item, order_invoices.total_qty_item, order_invoices.total_invoice as order_invoice, order_invoices.cash, order_invoices.left_payment, order_invoices.created_at as order_date, order_item_details.qty, order_item_details.product_name, order_item_details.process_name, order_item_details.status_order_item, order_item_details.unit_price, order_item_details.total_price").where("invoice_masters.id = ?", invoice_master_id).order("order_invoices.invoice_number")
    return scope
  end

end

app/views/invoices/_list.html.erb
<% if notice.present? %>
  <div class="row">
    <div class="col-md-12">
      <div class="warning-section">
        <div class="warning-icon">
          <i class="icon icon-attention"></i>
        </div>
        <p>
          <%= notice %>
        </p>
      </div>
    </div>
  </div>
<% end %>

<div class="card-white card-table">
  <div class="header-card">
    <div class="header-card-title">
      <div>
        <span class="header-icon"><i class="icon icon-docs"></i></span>
        <span>List Invoices</span>
      </div>
    </div>
  </div>
  <div class="body-card">
    <%= form_for(invoices_path, method: :get, remote: true) do %>
      <div class="row filter">
        <div class="col-md-8">
          <span>Show</span>
          <%= select_tag "per_page", options_for_select([[10, 10], [20, 20], [30, 30], [40, 40]], params[:per_page]), {class: "form-control show-entries"} %>
          <span>Entries</span>
        </div>
        <div class="col-md-4">
          <div class="form-group row">
            <label for="searcho" class="col-sm-2 col-form-label">Search:</label>
            <div class="col-sm-10"> 
              <div class="input-group mb-3">
                <%= text_field_tag "search", {}, class: "form-control", placeholder:"cari berdasakan nama customer atau nomor pesanan", value: params[:search] %>
                <div class="input-group-append">
                  <button type="submit"class="btn btn-outline-default btn-search" type="button"><i class="icon icon-search"></i></button>
                </div>
              </div>
            </div>
          </div>
          <%= hidden_field_tag 'start_date', @start_date.to_date.strftime("%d-%m-%Y") %>
          <%= hidden_field_tag 'end_date', @end_date.to_date.strftime("%d-%m-%Y") %>
        </div>
      </div>
    <% end %>

    <div class="table-responsive center">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th>Invoice Number</th>
            <th>Customer Name</th>
            <th>Invoice Date</th>
            <th>Total</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% if invoices.blank? %>
            <tr><td colspan="7" class="center"> Data tidak ditemukan </td></tr>
          <% end %>
          <% invoices.each_with_index do |invoice, index| %>
            <tr>
              <% per_page = params[:per_page].present? ? params[:per_page].to_i : 10 %>
              <td><%= index+1 + (params[:page].present? ? per_page*(params[:page].to_i - 1) : 0) %></td>
              <td><%= invoice.invoice_master_code %></td>
              <td><%= invoice.customer_name %></td>
              <td><%= invoice.invoice_date.to_date.strftime("%d %b %Y") %></td>
              <td><%= invoice.total_invoice %></td>
              <td><%= invoice.status_invoice %></td>
              <td>
                <%= link_to raw("<i class='icon icon-search'></i>"), invoice_path(invoice.id)+"/detail", class: "btn btn-info btn-action" %>

                <%= link_to raw("<i class='icon icon-print'></i>"), "javascript:void();", :'data-link' => invoice_path(invoice), :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Invoice #{invoice.invoice_master_code} | #{invoice.customer_name}", class: "btn btn-info btn-action launch_modal" %>
                
                <%= link_to raw("<i class='icon icon-edit'></i>"), edit_invoice_path(invoice.id), :'data-link' => edit_invoice_path(invoice.id), :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Update Invoice #{invoice.invoice_master_code}", class: "btn btn-outline-warning btn-action launch_modal" %>

                <%= link_to raw("<button class='btn btn-outline-danger btn-action'><i class='icon icon-trash'></i></button>"), invoice_path(invoice), method: :delete, data: {confirm: "Are you sure ?"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div style="display:flex; justify-content: center;">
        <%= paginate invoices %>
      </div>
      <%= page_entries_info invoices, :entry_name => "Invoice" %>
    </div>
  </div>
</div>

<div class="modal fade" id="modal_show" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document" style="max-width: 990px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Loading...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="loading">
          <img src="/assets/loading.gif">
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "filter_date.js" %>
<%= javascript_include_tag "invoices.js" %>

app/views/invoices/detail.html.erb
<% if notice.present? %>
  <div class="row">
    <div class="col-md-12">
      <div class="warning-section">
        <div class="warning-icon">
          <i class="icon icon-attention"></i>
        </div>
        <p>
          <%= notice %>
        </p>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="card-white card-table">
      <div class="header-card">
        <div class="header-card-title">
          <div>
            <span class="header-icon"><i class="icon icon-doc-text"></i></span>
            <span>Invoice</span>
          </div>
          <div>
            <%= link_to raw("<i class='icon icon-edit'></i> Edit"), edit_invoice_path(@invoice.id), :'data-link' => edit_invoice_path(@invoice.id), :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Update Invoice #{@invoice.invoice_master_code}", class: "btn btn-outline-warning btn-action launch_modal" %>
          </div>
        </div>
      </div>
      <div class="body-card">
        <div class="invoice-master-detail">
          <div class="row">
            <div class="col-md-3">Tanggal</div>
            <div class="col-md-9"><%= @invoice.created_at.to_date.strftime("%d %B %Y") %></div>
          </div>
          <div class="row">
            <div class="col-md-3">Code Invoice</div>
            <div class="col-md-9"><%= @invoice.invoice_master_code %></div>
          </div>
          <div class="row">
            <div class="col-md-3">Customer Name</div>
            <div class="col-md-9"><%= @invoice.customer.customer_name %></div>
          </div>
          <div class="row">
            <div class="col-md-3">Jumlah Transaksi</div>
            <div class="col-md-9"><%= @invoice.invoice_details.count %></div>
          </div>
          <div class="row">
            <div class="col-md-3">Total Invoice</div>
            <div class="col-md-9">Rp. <%= number_to_rupiah(@invoice.total_invoice) %></div>
          </div>
          <!-- <div class="row">
            <div class="col-md-3">Status</div>
            <div class="col-md-9"><%= @invoice.status_invoice.eql?('new') ? "BELUM LUNAS" : "LUNAS" %></div>
          </div> -->
          <% if @invoice.status_invoice.eql?('done') %>
            <div class="row">
              <div class="col-md-3">Tanggal Bayar</div>
              <div class="col-md-9"><%= @invoice.updated_at.to_date.strftime("%d %B %Y") %></div>
            </div>
          <% end %>
        </div>
        <div class="list-transaksi">
          <button class="btn btn-default color-purple martop trigger-transaksi"> List transaksi </button>
          <div class="row show-list-transaksi-master" style="display: none;">
            <% @invoice.invoice_details.each do |detail| %>
              <div class="col-md-12" style="border-top:1px dashed #adadad; padding:30px; margin-top:20px;">
                <div class="row">
                  <div class="col-md-6">
                    <div class="row">
                      <div class="col-md-4">
                        Nomor Surat Jalan :
                      </div>
                      <div class="col-md-6">
                        <%= link_to detail.order_invoice.invoice_number, orders_path(start_date: detail.order_invoice.created_at.to_date, search: detail.order_invoice.invoice_number) %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                        Tanggal Transaksi :
                      </div>
                      <div class="col-md-8">
                        <%= detail.order_invoice.created_at.to_date.strftime("%d %B %Y") %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="row">
                      <div class="col-md-4">
                        Total Transaksi :
                      </div>
                      <div class="col-md-8">
                        Rp. <%= number_to_rupiah(detail.order_invoice.total_invoice) %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                        Total Cash :
                      </div>
                      <div class="col-md-8">
                        Rp. <%= number_to_rupiah(detail.order_invoice.cash) %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                        Sisa Bayar :
                      </div>
                      <div class="col-md-8">
                        Rp. <%= number_to_rupiah(detail.order_invoice.left_payment) %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <table class="table" style="border:0px;">
                      <tr>
                        <td style="border:0px;">Nama Barang</td>
                        <td style="border:0px;">Process</td>
                        <td style="border:0px;">qty</td>
                        <td style="border:0px;">Item price</td>
                        <td style="border:0px;">Total price</td>
                      </tr>
                      <% detail.order_invoice.order_item_details.each do |item| %>
                        <tr>
                          <td style="border:0px;"> <%= item.product_name %> </td>
                          <td style="border:0px;"> <%= item.process_name %> </td>
                          <td style="border:0px;"> <%= item.qty %> </td>
                          <td style="border:0px;"> <%= item.unit_price %> </td>
                          <td style="border:0px;"> <%= item.total_price %> </td>
                        </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>


        <div class="row">
          <div class="col-md-12 right">
              <%= link_to raw("<i class='icon icon-print'></i> Print"), "javascript:void();", :'data-link' => invoice_path(@invoice), :'data-toggle' => 'modal', :'data-target' => '#modal_show', :'data-title' => "Invoice #{@invoice.invoice_master_code} | #{@invoice.customer.customer_name}", class: "btn btn-info btn-action launch_modal" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal_show" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document" style="max-width: 990px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Loading...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="loading">
          <img src="/assets/loading.gif">
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "invoices.js" %>

app/views/invoices/edit.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Loading...</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-md-12">
        <div class="card-white card-table">
          <div class="header-card">
            <div class="header-card-title">
              <div>
                <span class="header-icon"><i class="icon icon-doc-text"></i></span>
                <span>Invoice</span>
              </div>
            </div>
          </div>
          <div class="body-card">
            <%= form_for @invoice, :as => :post, :url => invoice_path(@invoice), remote: true do |f| %>
              <div class="invoice-master-detail">
                <div class="row">
                  <div class="col-md-3">Tanggal</div>
                  <div class="col-md-9"><%= @invoice.created_at.to_date.strftime("%d %B %Y") %></div>
                </div>
                <div class="row">
                  <div class="col-md-3">Code Invoice</div>
                  <div class="col-md-9"><%= @invoice.invoice_master_code %></div>
                </div>
                <div class="row">
                  <div class="col-md-3">Customer Name</div>
                  <div class="col-md-9"><%= @invoice.customer.customer_name %></div>
                </div>
                <div class="row">
                  <div class="col-md-3">Jumlah Transaksi</div>
                  <div class="col-md-9"><%= @invoice.invoice_details.count %></div>
                </div>
                <div class="row">
                  <div class="col-md-3">Total Invoice</div>
                  <div class="col-md-9">Rp. <%= number_to_rupiah(@invoice.total_invoice) %></div>
                </div>
                <div class="row">
                  <div class="col-md-3">Status</div>
                  <div class="col-md-9"><%= f.select :status_invoice, options_for_select([["Belum Lunas", "new"], ["Lunas", "done"]], @invoice.status_invoice), {}, class: "form-control", readonly: "readonly" %> </div>
                </div>
              </div>        
              <button type="submit" class="btn btn-primary color-purple martop trigger-transaksi"> Save </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
<%= render "list", invoices: @invoices %>

app/views/invoices/login_print.html.erb
<div class="modal fade" id="modal_login_print" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Login Menggunakan Akun Supervisor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Surat Jalan ini telah di cetak sebelumnya, untuk mencetaknya kembali masukan login user yg berwenang</p>
        <%= form_tag login_check_print_invoices_path, :remote => true do |f| %>
          <div class="form-group">
            <%= label_tag :email %>
            <%= text_field_tag :email, "", class: "form-control", placeholder: "Email" %>
          </div>
          <div class="form-group">
            <%= label_tag :password %>
            <%= password_field_tag :password, "", class: "form-control", placeholder: "Password" %>
          </div>
          <div class="form-group">
            <%= submit_tag "Confirm Login", class: "btn btn-custom btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/invoices/show.html.erb
<style>
  .modal-body th{padding: 3px!important; color:black!important; font-size: 11pt; font-weight: bold;}
  .modal-body td{padding: 3px!important; color:black!important; font-size: 11pt; font-weight: bold;}
  .modal-body h4{font-size: 14pt}
  .modal-body {font-size: 14pt}
  .signature {font-size: 11pt; font-weight: bold; color: #000;}
  .center {text-align: center;}
  .big-font {font-size: 14pt; font-weight: bold;}
  .font-info-header {font-size:11pt; font-weight: bold;}
</style>
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Loading...</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    
    <div class="invoice-detail">
      <div class="row">
        <div class="col-md-6">
          <h4 class="small-title" style="color:black!important;"> GREES DENIM </h4>
          <p style="margin-bottom: 0px; font-size:10pt; color:black!important; font-weight: bold;">Jl. Kp. Cikadu Tengah <br />
          Ds, Sukamulya Kec. Kutawaringin - Bandung <br />
          No. Telp. 0812 2122 2291, 0856 2445 556 <br />
          <%= Time.now.strftime("%d-%m-%Y %H:%M:%S") %>
        </div>
        <!-- <div class="col-md-3 font-info-header" style="float: right;">
          <div class="martop">Invoice Date :</div>
          <span><%= @invoice.created_at.to_date.strftime("%d %B %Y") %></span>

          <div class="martop">Invoice Id :</div>
          <span><%= @invoice.invoice_master_code %></span>
        </div>
        <div class="col-md-3 font-info-header" style="float: right;">
          <div class="martop">Billed To : </div>
          <div>
            <%= @invoice.try(:customer).try(:customer_name) %> <br />
            <%= @invoice.try(:customer).try(:address) %> <br />
            <%= @invoice.try(:customer).try(:phone) %> <br />
          </div>
        </div> -->
      </div>

      <div class="row" style="margin-top:5px;">
        <div class="col-md-12">
          <div class="center bold"><h4 class="big-font"><%= @invoice.status_invoice.eql?('new') ? "INVOICE" : "INVOICE" %></h4></div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div style="display:flex; justify-content: space-between;">
            <div>
              <table>
                <tr><td>Customer</td> <td>:</td> <td><%= @invoice.try(:customer).try(:customer_name) %></td></tr>
              </table>
            </div>
            <div>
              <table>
                <tr>
                  <td>Tanggal</td>
                  <td>:</td>
                  <td><%= @invoice.created_at.to_date.strftime("%d %B %Y") %></td>
                </tr>
                <tr>
                  <td>No</td>
                  <td>:</td>
                  <td><%= @invoice.invoice_master_code %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div class="row martop" style="margin-top:5px;">
        <div class="col-md-12">
          <table class="table table-bordered" style="border:0px; text-align: center;">
            <thead>
              <tr>
                <th>Tanggal</th>
                <th>Nomor Surat Jalan</th>
                <th>Nama Barang</th>
                <th>Process</th>
                <th>Qty</th>
                <th>Harga</th>
                <th>Jumlah</th>
              </tr>
            </thead>
            <tbody>
              <% invoice_details = find_invoice_detail(@invoice.id) %>
              <% order_number = Array.new %>
              <% total      = 0 %>
              <% total_cash = 0 %>
              <% total_pay = 0 %>
              <% total_qty = 0 %>
              <% invoice_details.each_with_index do |value, index| %>
                <tr>
                  <% unless order_number.include?(value.order_number) %>
                    <td rowspan="<%= value.order_total_item %>"><%= value.order_date.to_date.strftime("%d/%m/%Y") %></td>
                    <td rowspan="<%= value.order_total_item %>"><%= value.order_number %></td>
                  <% end  %>
                  <td><%= value.product_name %></td>
                  <td><%= value.process_name %></td>
                  <td><%= value.qty %></td>
                  <td>Rp. <%= number_to_rupiah(value.unit_price) %></td>
                  <td>Rp. <%= number_to_rupiah(value.total_price) %></td>
                  <% unless order_number.include?(value.order_number) %>
                    <!-- <td rowspan="<%# value.order_total_item %>">Rp. <%= number_to_rupiah(value.order_invoice) %></td>
                    <td rowspan="<%# value.order_total_item %>">Rp. <%= number_to_rupiah(value.cash) %></td>
                    <td rowspan="<%# value.order_total_item %>">Rp. <%= number_to_rupiah(value.left_payment) %></td>
                    <%# total_cash += value.cash.to_i %>
                    <%# total_pay  += value.left_payment.to_i %> -->
                    <% total     += value.order_invoice.to_i %>
                    <% order_number.push(value.order_number) %>
                  <% end %>
                  <% total_qty += value.qty.to_i %>
                </tr>
              <% end %>
              <!-- <tr>
                <td colspan="7" class="right" style="border: 0px;">Sub Total</td>
                <td colspan="3" style="border: 0px;">Rp. <%# number_to_rupiah(total) %></td>
              </tr>
              <tr>
                <td colspan="7" class="right" style="border: 0px;">Total Cash</td>
                <td colspan="3" style="border: 0px;">Rp. <%# number_to_rupiah(total_cash) %></td>
              </tr> -->
              <tr style="background-color: #; color:#fff;">
                <td colspan="4" class="left">Total</td>
                <td ><%= total_qty %></td>
                <td></td>
                <td>Rp. <%= number_to_rupiah(total) %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <% if @invoice.status_invoice.eql?('done') %>
          <div class="col-md-12 center">
            * Dibayar pada tanggal <%= @invoice.updated_at.to_date.strftime("%d %B %Y") %>
          </div>
        <% end %>
      </div>

      <div class="row martop" style="margin-bottom: 40px;">
        <table>
          <tr><td>Note</td><td>:</td><td colspan="2">Lebih dari 1 minggu komplain tidak dilayani</td></tr>
          <tr><td></td><td></td><td colspan="2">Pembayaran di transfer ke rekening atas nama ibu <b>SARAH MARDIAH</b></td></tr>
          <tr><td></td><td></td><td><b># BCA</b></td><td>: 3790309536</td></tr>
          <tr><td></td><td></td><td><b># Mandiri</b></td><td>: 130 00 1552182 9</td></tr>
          <tr><td></td><td></td><td><b># BNI</b></td><td>: 0438001869</td></tr>
        </table>
      </div>

      <div style="width:100%; display: flex; justify-content: space-between;" class="signature">
        <div class="col-md-3">
          <p style="text-align:center;">Penerima</p>
          <div style="margin-top:70px; display:flex; justify-content: space-between;">
            <span style="padding-right: 100px;">(</span><span>)</span>
          </div>
        </div>

        <div class="col-md-3" style="float:right;">
          <p style="text-align:center;">Admin</p>
          <div style="margin-top:70px; display:flex; justify-content: space-between;">
            <span>(</span> <%= @current_user.fullname %> <span>)</span>
          </div>
        </div>
      </div>

    </div>

  </div>
  <div class="modal-footer">
    <button type='button' class='btn btn-secondary btn-custom' data-dismiss='modal'>Tutup</button> 
    <a href='javascript:void(0)'><button type='button' class='btn btn-primary btn-custom print' data-link="<%= print_count_invoices_path %>" data-invoiceid="<%= @invoice.id %>" data-printcount="<%= @invoice.print_count.present? ? @invoice.print_count + 1 : 1 %>">Print</button></a>
  </div>
</div>

<%= javascript_include_tag "invoices_show" %>

app/views/invoices/update.js.erb
console.log("<%= notice %>")