config/routes.rb
Rails.application.routes.draw do
  resources :jenis_proses
  get 'role_denieds/index', as: "role_denieds"
  get 'invoices/index'
  root 'home#index'
  
  resources :trash_recordings
  resources :customer_achievements, only: [:index] do 
    collection do
      get :transaction_list
    end
  end
  resources :inventory_histories
  resources :customers
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders do 
    collection do 
      get :add_item
      get :get_customers
      get :get_jenis_proses
      get :autocomplete_customer_customer_name
      get :confirm_new
      post :confirm_new
      get :print_count
      get :login_print
      post :login_check_print
    end
  end
  resources :inventories do
    collection do
      get ':id/add', action: :add, as: :add
    end
  end
  resources :order_ins
  resources :order_outs
  resources :invoices do
    collection do
      get ':id/detail', action: :detail
      get :transaction_list
      get :print_count
      get :login_print
      post :login_check_print
    end
  end

  resources :roles do
    collection do 
      post ':id/update_role_user', action: :update_role_user, :as => :update_role_user
    end
  end

  get 'dashboard', to: 'home#index', as: 'dashboard'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/views/shared/_footer.html.erb
<div class="row">
  <div class="col-md-12 footer">
    <h4>2019 © MAV</h4>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="f-header">
  <div class="left-col-header">    
      <% if @current_user %>
        <%= link_to raw("<button class='btn btn-custom btn-logout btn-space-icon'> <i class='icon icon-logout'></i> Logout</button>"), logout_path %>
      <% end %>
  </div>
  <div class="right-col-header">
    <a href="#" class="col-menu">
      <span class="icon-col-menu"><i class="icon icon-bell"></i></span>
    </a>
    <a href="#" class="col-menu">
      <% if @current_user %>
        <span class="welcome-text">Hi, <%= @current_user.fullname.present? ? @current_user.fullname.titleize : @current_user.username.present? ? @current_user.username.titleize : @current_user.email %></span>
      <% end %>
      <span class="icon-col-menu"><i class="icon icon-user-circle-o"></i></span>
    </a>
  </div>
</div>
<div class="f-sub-header">
  <div class="breadcrumbs">
    <ul class="breadcrumb-list clearfix">
      <li class="breadcrumb-item"><%= params[:controller].titleize %></li>
      <li class="breadcrumb-item"><%= params[:action].titleize %></li>
    </ul>
  </div>
  <% if !@hide_filter %>
    <div class="additional-menus">
      <div class="wrapper">
        <% params_for_request = Hash.new %>
        <% params.each do |key, value| %>
          <% params_for_request[key] = value unless key.eql?("action") && value.eql?("controller") %>
        <% end %>
        <%= link_to raw('<button class="btn btn-custom btn-transparent btn-today"> Today </button>'), request.path+"?start_date="+Date.today.to_s, class: "filter-date-today", remote: true %>
        <%= link_to raw('<button class="btn btn-custom btn-transparent btn-month"> Month </button>'), request.path+"?start_date="+Date.today.beginning_of_month.to_s+"&end_date="+Date.today.to_s, class: "filter-date-month", remote: true %>
        <%= link_to raw('<button class="btn btn-custom btn-transparent btn-year"> Year </button>'), request.path+"?start_date="+Date.today.beginning_of_year.to_s+"&end_date="+Date.today.to_s, class: "filter-date-year", remote: true %>

        
        <button id="btn-custom-date" class="btn btn-custom btn-custom btnc-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
          <span class="time-filter-tag"><%= params[:start_date].present? ? "Tanggal" : "This Week" %>: </span>
          <span class="color-purple time-filter"> <%= @start_date.to_date.strftime("%b %d") + ' - ' + @end_date.to_date.strftime("%b %d") if (@start_date.present? && @end_date.present?) or (params[:start_date].present? && params[:end_date].present?) %></span> 
          <i class="icon icon-calendar-check-o color-purple"></i> 
        </button>
        <div class="dropdown-menu">
          <div class="dropdown-select-date">
            <%= form_tag(request.path, method: :get, remote: true) do %>
              <div class="form-group">
                <label>Start Date:</label>
                <input type="text" class="form-control" id="filter-start-date" name="start_date" autocomplete="off" value="<%= @start_date.to_date.strftime('%d-%m-%Y') %>">
              </div>
              <div class="form-group">
                <label>End Date:</label>
                <input type="text" class="form-control" id="filter-end-date" name="end_date" autocomplete="off", value="<%= @end_date.to_date.strftime('%d-%m-%Y') %>">
                <%= hidden_field_tag "custom_date", "true" %>
              </div>
              <button type="submit" class="btn btn-custom btn-primary btn-close-date">Submit</button>
              <button type="button" class="btn btn-custom btn-default btn-close-date">Cancel</button>
            <% end %>
          </div>
        </div>
        <i class="icon icon-calendar"></i>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<div class="brand-sidebar">
  <div class="brand-logo">
    <a href="#">GREES DENIM</a>
  </div>
  <div class="icon-aside">
    <i class="icon icon-angle-double-left"></i>
  </div> 
</div>

<div class="menu-sidebar">
  <div class="wrapper-menu">
    <ul class="menu-lists">
      
      <% if list_role_menu.include?("Dashboard") %>
        <li class="item-menu">
          <%= link_to root_path, class: "link-item-menu #{(params[:controller] == 'home' && params[:action] == 'index') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon  icon-gauge"></i>
            </span>
            <span class="text-menu"> Dashboard </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Create Transaction") %>
        <li class="item-menu-title">
          <h4>Order</h4>
        </li>
      <% end %>

      <% if list_role_menu.include?("Create Transaction") %>
        <li class="item-menu">
          <%= link_to new_order_path, class: "link-item-menu #{(params[:controller] == 'orders' && params[:action] == 'new') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-basket"></i>
            </span>
            <span class="text-menu"> Buat Pesanan Baru </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("List Transaction") %>
        <li class="item-menu">
          <%= link_to orders_path, class: "link-item-menu #{(params[:controller] == 'orders' && params[:action] == 'index' && params[:status].blank?) ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-th-large"></i>
            </span>
            <span class="text-menu"> List Semua Pesanan </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("List Transaction") %>
        <li class="item-menu">
          <%= link_to orders_path(:status=>"done"), class: "link-item-menu #{(params[:controller] == 'orders' && params[:action] == 'index' && params[:status].present?) ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-ok-circled2"></i>
            </span>
            <span class="text-menu"> List Pesanan Selesai </span>
          <% end %>        
        </li>
      <% end %>

      <% if list_role_menu.include?("List Transaction") %>
        <li class="item-menu">
          <%= link_to customer_achievements_path, class: "link-item-menu #{(params[:controller] == 'customer_achievements' && params[:action] == 'index') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-box"></i>
            </span>
            <span class="text-menu"> Customer Total Order </span>
          <% end %>        
        </li>
      <% end %>

      <% if list_role_menu.include?("Barang In Progress") %>
        <li class="item-menu">
          <%= link_to order_ins_path, class: "link-item-menu #{(params[:controller] == 'order_ins' && params[:action] == 'index') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-right-circled"></i>
            </span>
            <span class="text-menu"> Barang In Progress </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Barang Completed") %>
        <li class="item-menu">
          <%= link_to order_outs_path, class: "link-item-menu #{(params[:controller] == 'order_outs' && params[:action] == 'index') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-left-circled"></i>
            </span>
            <span class="text-menu"> Barang Completed </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Create Invoice") %>
        <li class="item-menu-title">
          <h4>Invoice</h4>
        </li>
      <% end %>

      <% if list_role_menu.include?("Create Invoice") %>
        <li class="item-menu">
          <%= link_to new_invoice_path, class: "link-item-menu #{(params[:controller] == 'invoices' && params[:action] == 'new') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-doc"></i>
            </span>
            <span class="text-menu"> Buat Invoice </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("List Invoice") %>
        <li class="item-menu">
          <%= link_to invoices_path, class: "link-item-menu #{(params[:controller] == 'invoices' && params[:action] == 'index') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-docs"></i>
            </span>
            <span class="text-menu"> Invoice </span>
          <% end %>
        </li>
      <% end %>

      <!-- <li class="item-menu-title">
        <h4>Report</h4>
      </li>

      <li class="item-menu">
        <a class="link-item-menu" href="#">
          <span class="wrap-icon-menu">
            <i class="icon icon-money"></i>
          </span>
          <span class="text-menu"> Laporan Invoice </span>
        </a>
      </li>

      <li class="item-menu">
        <a class="link-item-menu" href="#">
          <span class="wrap-icon-menu">
            <i class="icon icon-truck"></i>
          </span>
          <span class="text-menu"> Laporan Masuk & Keluar </span>
        </a>
      </li> -->

      <% if list_role_menu.include?("Master Inventory") %>
        <li class="item-menu-title">
          <h4>Inventory</h4>
        </li>
      <% end %>

      <% if list_role_menu.include?("Master Inventory") %>
        <li class="item-menu">
          <%= link_to inventories_path, class: "link-item-menu #{(params[:controller] == 'inventories') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-box"></i>
            </span>
            <span class="text-menu"> Inventory </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("History Inventory") %>
        <li class="item-menu">
          <%= link_to inventory_histories_path, class: "link-item-menu #{(params[:controller] == 'inventory_histories') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-exchange"></i>
            </span>
            <span class="text-menu"> History Inventory </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Inventory Sampah") %>
        <li class="item-menu">
          <%= link_to trash_recordings_path, class: "link-item-menu #{(params[:controller] == 'trash_recordings') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-trash"></i>
            </span>
            <span class="text-menu"> Inventory Sampah </span>
          <% end %>
        </li>
      <% end %>

      <!-- <li class="item-menu">
        <%= link_to inventory_histories_path, class: "link-item-menu #{(params[:controller] == 'inventory_histories' && params[:type].blank? ) ? 'active-menu' : ''}" do %>
          <span class="wrap-icon-menu">
            <i class="icon icon-history"></i>
          </span>
          <span class="text-menu"> All History Inventory </span>
        <% end %>
      </li>

      <li class="item-menu">
        <%= link_to inventory_histories_path(type: "stok"), class: "link-item-menu #{(params[:controller] == 'inventory_histories' && params[:type] == "stok") ? 'active-menu' : ''}" do %>
          <span class="wrap-icon-menu">
            <i class="icon icon-clone"></i>
          </span>
          <span class="text-menu"> Stok Inventory </span>
        <% end %>
      </li> -->

      <li class="item-menu-title">
        <h4>Master Data</h4>
      </li>

      <% if list_role_menu.include?("Master Customer") %>
        <li class="item-menu">
          <%= link_to customers_path, class: "link-item-menu #{(params[:controller] == 'customers') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-users"></i>
            </span>
            <span class="text-menu"> Master Customer </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Master Jenis Proses") %>
        <li class="item-menu">
          <%= link_to jenis_proses_path, class: "link-item-menu #{(params[:controller] == 'jenis_proses') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-shower"></i>
            </span>
            <span class="text-menu"> Master Jenis Proses </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Master User") %>
        <li class="item-menu-title">
          <h4>User Management</h4>
        </li>
      <% end %>

      <% if list_role_menu.include?("Master User") %>
        <li class="item-menu">
          <%= link_to users_path, class: "link-item-menu #{(params[:controller] == 'customers') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-user"></i>
            </span>
            <span class="text-menu"> Master User </span>
          <% end %>
        </li>
      <% end %>

      <% if list_role_menu.include?("Role User") %>
        <li class="item-menu">
          <%= link_to roles_path, class: "link-item-menu #{(params[:controller] == 'roles') ? 'active-menu' : ''}" do %>
            <span class="wrap-icon-menu">
              <i class="icon icon-box"></i>
            </span>
            <span class="text-menu"> Role User </span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>