config/routes.rb
Rails.application.routes.draw do
  resources :jenis_proses
  get 'role_denieds/index', as: "role_denieds"
  get 'invoices/index'
  root 'home#index'
  
  resources :trash_recordings
  resources :customer_achievements, only: [:index] do 
    collection do
      get :transaction_list
    end
  end
  resources :inventory_histories
  resources :customers
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders do 
    collection do 
      get :add_item
      get :get_customers
      get :get_jenis_proses
      get :autocomplete_customer_customer_name
      get :confirm_new
      post :confirm_new
      get :print_count
      get :login_print
      post :login_check_print
    end
  end
  resources :inventories do
    collection do
      get ':id/add', action: :add, as: :add
    end
  end
  resources :order_ins
  resources :order_outs
  resources :invoices do
    collection do
      get ':id/detail', action: :detail
      get :transaction_list
      get :print_count
      get :login_print
      post :login_check_print
    end
  end

  resources :roles do
    collection do 
      post ':id/update_role_user', action: :update_role_user, :as => :update_role_user
    end
  end

  get 'dashboard', to: 'home#index', as: 'dashboard'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/trash_recording.rb
class TrashRecording < ApplicationRecord
  belongs_to :inventory
  belongs_to :user, foreign_key: :created_by

  before_save :set_default_value

  paginates_per 10

  def set_default_value
    if self.new_record?
      self.trash_date = Time.now
      self.status     = "active"
      self.is_deleted = false
    end
  end
end

app/controllers/trash_recordings_controller.rb
class TrashRecordingsController < ApplicationController
  before_action :current_user
  before_action :authenticate_user
  before_action :get_params_header, only: [:index, :show]
  before_action :get_parent, only: [:new, :edit]
  before_action :set_trash_recording, only: [:show, :edit, :update, :destroy]

  # GET /trash_recordings
  # GET /trash_recordings.json
  def index;end

  # GET /trash_recordings/1
  # GET /trash_recordings/1.json
  def show
  end

  # GET /trash_recordings/new
  def new
    @trash_recording = TrashRecording.new
    render layout: false
  end

  # GET /trash_recordings/1/edit
  def edit;end

  # POST /trash_recordings
  # POST /trash_recordings.json
  def create
    params[:trash_recording][:created_by] = @current_user.id
    @trash_recording = TrashRecording.new(trash_recording_params)

    respond_to do |format|
      if @trash_recording.save
        format.html { redirect_to @trash_recording, notice: 'Trash recording was successfully created.' }
        format.json { render :show, status: :created, location: @trash_recording }
      else
        format.html { render :new }
        format.json { render json: @trash_recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trash_recordings/1
  # PATCH/PUT /trash_recordings/1.json
  def update
    respond_to do |format|
      if @trash_recording.update(trash_recording_params)
        format.html { redirect_to @trash_recording, notice: 'Trash recording was successfully updated.' }
        format.json { render :show, status: :ok, location: @trash_recording }
      else
        format.html { render :edit }
        format.json { render json: @trash_recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trash_recordings/1
  # DELETE /trash_recordings/1.json
  def destroy
    @trash_recording.destroy
    respond_to do |format|
      format.html { redirect_to trash_recordings_url, notice: 'Trash recording was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_parent
      @inventories = Inventory.order(:name)
    end

    def get_params_header
      @start_date = params[:start_date].present? ? params[:start_date] : Time.now - 7.days
      @end_date = params[:end_date].present? ? params[:end_date] : Time.now
      @trash_recordings = TrashRecording.joins(:inventory).where("DATE(trash_recordings.created_at) between ? and ? and inventories.name like ?", @start_date, @end_date, "%#{params[:search]}%").order("created_at desc")
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_trash_recording
      @trash_recording = TrashRecording.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trash_recording_params
      params.require(:trash_recording).permit(:trash_date, :inventory_id, :created_by, :qty, :status, :is_deleted)
    end
end

app/helpers/trash_recordings_helper.rb
module TrashRecordingsHelper
end

app/views/trash_recordings/_filter.html.erb
<%= form_for(trash_recordings_path, method: :get, remote: true) do %>
  <div class="row filter">
    <div class="col-md-8">
      <span>Show</span>
      <%= select_tag "per_page", options_for_select([[10, 10], [20, 20], [30, 30], [40, 40]], per_page), {class: "form-control show-entries"} %>
      <span>Entries</span>
    </div>
    <div class="col-md-4">
      <div class="form-group row">
        <label for="searcho" class="col-sm-2 col-form-label">Search:</label>
        <div class="col-sm-10"> 
          <div class="input-group mb-3">
            <%= text_field_tag "search", {}, class: "form-control", placeholder:"Cari berdasarkan nama barang inventory", value: search %>
            <div class="input-group-append">
              <button type="submit"class="btn btn-outline-default btn-search" type="button"><i class="icon icon-search"></i></button>
            </div>
          </div>
        </div>
      </div>
      <%= hidden_field_tag 'start_date', start_date.present? ? start_date.to_date.strftime("%d-%m-%Y") : nil %>
      <%= hidden_field_tag 'end_date', end_date.present? ? end_date.to_date.strftime("%d-%m-%Y") : nil %>
    </div>
  </div>
<% end %>

app/views/trash_recordings/_flash.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="warning-section">
      <div class="warning-icon">
        <i class="icon icon-attention"></i>
      </div>
      <p>
        <%= notice %>
      </p>
    </div>
  </div>
</div>

app/views/trash_recordings/_form.html.erb
<%= form_with(model: trash_recording, local: true, remote: true) do |form| %>
  <% if trash_recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trash_recording.errors.count, "error") %> prohibited this trash_recording from being saved:</h2>

      <ul>
      <% trash_recording.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :inventory_id %>
    <%= form.select(:inventory_id, inventories.map{|iv| [iv.name_code, iv.id]}, {prompt: "-- Pilih Barang --"}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= form.label :qty_trash %>
    <%= form.number_field :qty, class: "form-control", style: "width: 150px;" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-success btn-custom" %>
  </div>
<% end %>

app/views/trash_recordings/_list.html.erb
<div class="table-responsive center">
  <table class="table table-hover table-busered">
    <thead>
      <tr>
        <th>No</th>
        <th>Trash Date</th>
        <th>Inventory (Barang)</th>
        <th>Created By</th>
        <th>Qty</th>
      </tr>
    </thead>
    <tbody>
      <% trash_recordings.each_with_index do |trash, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= trash.trash_date.try(:to_date).try(:strftime, "%d %B %Y") %></td>
          <td><%= trash.try(:inventory).try(:name) %></td>
          <td><%= trash.try(:user).try(:fullname) %></td>
          <td><%= trash.qty %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trash_recordings/_modal.html.erb
<div class="modal fade" id="modal_show" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document" style="max-width: 990px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Loading...</h5>
        <button type="button" class="close close-modal-trash" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="loading">
          <img src="/assets/loading.gif">
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/trash_recordings/edit.html.erb
<h1>Editing Trash Recording</h1>

<%= render 'form', trash_recording: @trash_recording %>

<%= link_to 'Show', @trash_recording %> |
<%= link_to 'Back', trash_recordings_path %>

app/views/trash_recordings/index.html.erb
<% if notice.present? %>
  <%= render 'flash', notice: notice %>
<% end %>

<div class="card-white card-table">
  <div class="header-card">
    <div class="header-card-title">
      <div>
        <span class="header-icon"><i class="icon icon-box"></i></span>
        <span>List Inventory</span>
      </div>
      <div>
        <%= link_to "Add Trash Record", "javascript:voide(0);", data: {link: new_trash_recording_path, toggle: 'modal', target: '#modal_show', title: "Add new trash record"}, class: "btn btn-success btn-custom launch-modal-trash-record" %>

        <%= link_to raw("<i class='icon icon-print'></i> Print"), "javascript:voide(0);", :"data-link" => new_inventory_history_path, :'data-toggle' => 'modal', :'data-target' => '#modal_print', :'data-title' => "Buat Pengeluaran Barang", class: "btn btn-primary btn-custom" %>
      </div>
    </div>
  </div>
  <div class="body-card">
    <div class="filter-trash">
      <%= render 'filter', per_page: params[:per_page], start_date: params[:start_date], end_date: params[:end_date], search: params[:search], status: params[:status], inventory_id: params[:inventory_id] %>
    </div>
    <div class="list-trash-record">
      <%= render 'list', trash_recordings: @trash_recordings %>
    </div>
  </div>
</div>

<div id="modal-for-trash">
  <%= render 'modal' %>
</div>

<div class="modal fade" id="modal_print" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document" style="max-width: 990px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Print Inventory <%= "#{params[:start_date]} - #{params[:end_date]}" if params[:start_date].present? %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="table-responsive center">
          <table class="table table-hover table-busered">
            <thead>
              <tr>
                <th>No</th>
                <th>Trash Date</th>
                <th>Inventory (Barang)</th>
                <th>Created By</th>
                <th>qty</th>
              </tr>
            </thead>
            <tbody>
              <% qty = 0 %>
              <% @trash_recordings.each_with_index do |trash, i| %>
                <tr>
                  <% qty += trash.qty.to_i %>
                  <td><%= i+1 %></td>
                  <td><%= trash.trash_date.try(:to_date).try(:strftime, "%d %B %Y") %></td>
                  <td><%= trash.try(:inventory).try(:name) %></td>
                  <td><%= trash.try(:user).try(:fullname) %></td>
                  <td><%= trash.try(:qty) %></td>
                </tr>
              <% end %>
              <tr>
                <td colspan="4" class="center"> Total </td>
                <td><%= qty %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <a href='javascript:void(0)'>
          <button type='button' class='btn btn-primary btn-custom print' onclick="print()">Print</button>
        </a>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "trash_recordings" %>

app/views/trash_recordings/new.html.erb
<%= render 'form', trash_recording: @trash_recording, inventories: @inventories %>

app/views/trash_recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trash date:</strong>
  <%= @trash_recording.trash_date %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @trash_recording.inventory_id %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @trash_recording.created_by %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @trash_recording.qty %>
</p>

<p>
  <strong>Status:</strong>
  <%= @trash_recording.status %>
</p>

<p>
  <strong>Is deleted:</strong>
  <%= @trash_recording.is_deleted %>
</p>

<%= link_to 'Edit', edit_trash_recording_path(@trash_recording) %> |
<%= link_to 'Back', trash_recordings_path %>